# Not used yet!!! 
# For now, view and use config.py

project: MedSeg
runid: 0
focus: liver
mode: test
label_type: segmentation #pixelcount, binary
seed: 0
data_limit: None
srcpath: datasets/original

dst_path: datasets/preprocessed_2d

upper: 200
lower: -200
## volume depth (number of slices),
size: 48
## Cross sectional down scaling,
down_scale: 1
## Only use the liver and 20 slices of the liver as training samples,
expand_slice: 20
## Normalize the spacing of all data on the z-axis to 1mm,
slice_thickness: 1
##########################,
######### Model ##########,
##########################,
train_proportion: 0.8
drop_rate: 0.3
## Weight on losses 1, 2 and 3. Weight on loss 4 is 1.
alpha: 0.33
alpha_decay_rate: 0.98
num_workers: 2
## DataLoader does not support any more yet,
batch_size: 5
max_epochs: 200
## Optimizer and loss,
optim_opts: 
  lr: 0.001
lr_decay_rate: 0.90
loss_opts:
## Store model with metadata at given intervals.
checkpoint_interval: 3
init_2d_model_state: datasets/saved_states/runid_2013/VNet2d_runid_2013_epoch98.pth
init_model_state: None, #"datasets/saved_states/ResUnet_runid_12_epoch30.pth"

dst2d_slices_path: os.path.join(config["dst_2d_path"], 'slices/')
dst2d_labels_liver_path: os.path.join(config["dst_2d_path"], 'labels_liver/')
dst2d_labels_lesion_path: os.path.join(config["dst_2d_path"], 'labels_lesion/')
dst2d_pred_liver_path: os.path.join(config["dst_2d_path"], 'pred_liver/')
dst2d_pred_lesion_path: os.path.join(config["dst_2d_path"], 'pred_lesion/')
dst2d_fig_path: os.path.join(config["dst_2d_path"], "figures/")

