wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
alpha:
  desc: null
  value: 0.33
alpha_decay_rate:
  desc: null
  value: 0.98
batch_size:
  desc: null
  value: 5
checkpoint_interval:
  desc: null
  value: 5
data_limit:
  desc: null
  value: null
down_scale:
  desc: null
  value: 1
drop_rate:
  desc: null
  value: 0.3
dst2d_fig_path:
  desc: null
  value: datasets/preprocessed_2d/figures/
dst2d_labels_lesion_path:
  desc: null
  value: datasets/preprocessed_2d/labels_lesion/
dst2d_labels_liver_path:
  desc: null
  value: datasets/preprocessed_2d/labels_liver/
dst2d_pred_lesion_path:
  desc: null
  value: datasets/preprocessed_2d/pred_lesion/
dst2d_pred_liver_path:
  desc: null
  value: datasets/preprocessed_2d/pred_liver/
dst2d_slices_path:
  desc: null
  value: datasets/preprocessed_2d/slices/
dst_2d_path:
  desc: null
  value: datasets/preprocessed_2d/
dst_test_labels_lesion_path:
  desc: null
  value: datasets/preprocessed_quarter_size/test/labels_lesion/
dst_test_labels_liver_path:
  desc: null
  value: datasets/preprocessed_quarter_size/test/labels_liver/
dst_test_pred_lesion_path:
  desc: null
  value: datasets/preprocessed_quarter_size/test/pred_lesion/
dst_test_pred_liver_path:
  desc: null
  value: datasets/preprocessed_quarter_size/test/pred_liver/
dst_test_volumes_path:
  desc: null
  value: datasets/preprocessed_quarter_size/test/volumes/
dst_train_labels_lesion_path:
  desc: null
  value: datasets/preprocessed_quarter_size/train/labels_lesion/
dst_train_labels_liver_path:
  desc: null
  value: datasets/preprocessed_quarter_size/train/labels_liver/
dst_train_pred_lesion_path:
  desc: null
  value: datasets/preprocessed_quarter_size/train/pred_lesion/
dst_train_pred_liver_path:
  desc: null
  value: datasets/preprocessed_quarter_size/train/pred_liver/
dst_train_volumes_path:
  desc: null
  value: datasets/preprocessed_quarter_size/train/volumes/
dstpath:
  desc: null
  value: datasets/preprocessed_quarter_size/
expand_slice:
  desc: null
  value: 20
focus:
  desc: null
  value: liver
init_2d_model_state:
  desc: null
  value: null
init_model_state:
  desc: null
  value: null
label_type:
  desc: null
  value: binary
loss_opts:
  desc: null
  value: {}
lower:
  desc: null
  value: -200
lr_decay_rate:
  desc: null
  value: 0.9
max_epochs:
  desc: null
  value: 200
mode:
  desc: null
  value: train
num_workers:
  desc: null
  value: 2
optim_opts:
  desc: null
  value:
    lr: 0.01
project:
  desc: null
  value: MedSeg
runid:
  desc: null
  value: 1122020
seed:
  desc: null
  value: 0
size:
  desc: null
  value: 48
slice_thickness:
  desc: null
  value: 1
srcpath:
  desc: null
  value: datasets/original/
test_labels_path:
  desc: null
  value: datasets/original/test/seg/
test_volumes_path:
  desc: null
  value: datasets/original/test/ct/
train_labels_path:
  desc: null
  value: datasets/original/train/seg/
train_proportion:
  desc: null
  value: 0.8
train_volumes_path:
  desc: null
  value: datasets/original/train/ct/
upper:
  desc: null
  value: 200
