wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.5
alpha:
  desc: null
  value: 0.33
batch_size:
  desc: null
  value: 1
checkpoint_interval:
  desc: null
  value: 100
down_scale:
  desc: null
  value: 0.5
drop_rate:
  desc: null
  value: 0.3
dst_ct_path:
  desc: null
  value: datasets/preprocessed/train/ct/
dst_seg_path:
  desc: null
  value: datasets/preprocessed/train/seg/
dstpath:
  desc: null
  value: datasets/preprocessed/
expand_slice:
  desc: null
  value: 20
loss_opts:
  desc: null
  value: {}
lower:
  desc: null
  value: -200
max_epochs:
  desc: null
  value: 201
num_workers:
  desc: null
  value: 8
optim_opts:
  desc: null
  value:
    lr: 0.001
project:
  desc: null
  value: MedSeg
runid:
  desc: null
  value: 1
size:
  desc: null
  value: 48
slice_thickness:
  desc: null
  value: 1
srcpath:
  desc: null
  value: datasets/original/
test_ct_path:
  desc: null
  value: datasets/original/test/ct/
test_seg_path:
  desc: null
  value: datasets/original/test/seg/
train_ct_path:
  desc: null
  value: datasets/original/train/ct/
train_seg_path:
  desc: null
  value: datasets/original/train/seg/
upper:
  desc: null
  value: 200
